name: reseacue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^1.1.1
  flame: ^1.16.0
  flame_tiled: ^1.19.0
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  logging: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sfx/
    - assets/music/