name: reseacue
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flame: ^1.16.0
  flame_behaviors: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  intl: ^0.18.1
  logging: ^1.2.0
  package_info_plus: ^7.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  transparent_image: ^2.0.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sfx/
    - assets/music/
    - assets/images/
  fonts:
    - family: Digitalt
      fonts:
        - asset: fonts/Digitalt.ttf