name: reseacue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flame_behaviors: ^1.1.0
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  logging: ^1.2.0
  package_info_plus: ^4.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/sfx/
    - assets/music/
    - assets/images/
    - assets/audio/sfx/
  fonts:
    - family: Digitalt
      fonts:
        - asset: fonts/Digitalt.ttf